security:
  encoders:
    TrajetsBundle\Entity\Utilisateur: sha512

  role_hierarchy:
    ROLE_COLLECTEUR: ROLE_USER
    ROLE_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    utilisateurs:
      id: fos_user.user_provider.username_email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|console)|css|images|js)/
      security: false
    main:
      pattern:   ^/
      anonymous: true
      provider: utilisateurs
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path: fos_user_security_logout
        target: /login
      remember_me:
        secret: "%secret%"

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: ROLE_USER }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
